# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('eproj3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='eproj3.User')),
                ('metoo', models.ManyToManyField(related_name='metoo', to='eproj3.User')),
            ],
            managers=[
                ('wishManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
