# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eproj3', '0003_user_date_hired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_hired',
        ),
    ]
